// Code generated by "types-gen "; DO NOT EDIT.

package codec

// Coders
var (
	jsonCoder = json("json") // json Coder
	xmlCoder  = xml("xml")   // xml Coder
)

// An "Type does not implement 'Codec' as some methods are missing" compiler error signifies that the constant values have changed.
// Re-run the types-gen command to generate them again.
func _() {
	var _ Codec = jsonCoder
	var _ Codec = xmlCoder
}

// JsonMarshal
// 将obj解析为json字符串
func (Coders) JsonMarshal(v interface{}) (string, error) {
	return jsonCoder.Marshal(v)
}

// JsonUnmarshal
// 将obj解析为json字符串
func (Coders) JsonUnmarshal(data string, v interface{}) error {
	return jsonCoder.Unmarshal(data, v)
}

// XmlMarshal
// 将obj解析为xml字符串
func (Coders) XmlMarshal(v interface{}) (string, error) {
	return xmlCoder.Marshal(v)
}

// XmlUnmarshal
// 将obj解析为xml字符串
func (Coders) XmlUnmarshal(data string, v interface{}) error {
	return xmlCoder.Unmarshal(data, v)
}
